//js/playlist-export.js
// Playlist export utilities for XSPF and M3U formats

import { getTrackArtists, getTrackTitle } from './utils.js';

/**
 * Export playlist to XSPF format
 * @param {Object} playlist - Playlist object with name and tracks
 * @returns {string} XSPF XML content
 */
export function exportToXSPF(playlist) {
    const escapeXml = (str) => {
        if (!str) return '';
        return str
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&apos;');
    };

    const tracks = playlist.tracks || [];
    const trackListXml = tracks.map(track => {
        const title = escapeXml(getTrackTitle(track));
        const artist = escapeXml(getTrackArtists(track));
        const album = escapeXml(track.album?.title || '');
        const duration = track.duration ? track.duration * 1000 : 0; // XSPF uses milliseconds
        
        return `    <track>
      <title>${title}</title>
      <creator>${artist}</creator>
      <album>${album}</album>
      <duration>${duration}</duration>
    </track>`;
    }).join('\n');

    return `<?xml version="1.0" encoding="UTF-8"?>
<playlist version="1" xmlns="http://xspf.org/ns/0/">
  <title>${escapeXml(playlist.name || 'Untitled Playlist')}</title>
  <creator>Loop Music</creator>
  <date>${new Date().toISOString()}</date>
  <trackList>
${trackListXml}
  </trackList>
</playlist>`;
}

/**
 * Export playlist to M3U format
 * @param {Object} playlist - Playlist object with name and tracks
 * @returns {string} M3U content
 */
export function exportToM3U(playlist) {
    const tracks = playlist.tracks || [];
    
    const trackLines = tracks.map(track => {
        const title = getTrackTitle(track);
        const artist = getTrackArtists(track);
        const duration = Math.floor(track.duration || 0);
        
        // Extended M3U format
        return `#EXTINF:${duration},${artist} - ${title}\n# Album: ${track.album?.title || 'Unknown'}`;
    }).join('\n\n');

    return `#EXTM3U
#PLAYLIST:${playlist.name || 'Untitled Playlist'}
# Generated by Loop Music on ${new Date().toISOString()}

${trackLines}`;
}

/**
 * Export playlist to JSON format (for transfer between Loop instances)
 * @param {Object} playlist - Playlist object
 * @returns {string} JSON content
 */
export function exportToJSON(playlist) {
    return JSON.stringify({
        name: playlist.name,
        description: playlist.description || '',
        tracks: (playlist.tracks || []).map(t => ({
            id: t.id,
            title: getTrackTitle(t),
            artist: getTrackArtists(t),
            album: t.album?.title || '',
            duration: t.duration || 0,
            cover: t.album?.cover || ''
        })),
        exportedAt: new Date().toISOString(),
        source: 'Loop Music'
    }, null, 2);
}

/**
 * Download a playlist in the specified format
 * @param {Object} playlist - Playlist object
 * @param {string} format - 'xspf', 'm3u', or 'json'
 */
export function downloadPlaylist(playlist, format = 'xspf') {
    let content, mimeType, extension;
    
    switch (format.toLowerCase()) {
        case 'xspf':
            content = exportToXSPF(playlist);
            mimeType = 'application/xspf+xml';
            extension = 'xspf';
            break;
        case 'm3u':
            content = exportToM3U(playlist);
            mimeType = 'audio/mpegurl';
            extension = 'm3u';
            break;
        case 'json':
            content = exportToJSON(playlist);
            mimeType = 'application/json';
            extension = 'json';
            break;
        default:
            throw new Error(`Unknown format: ${format}`);
    }
    
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${sanitizeFilename(playlist.name || 'playlist')}.${extension}`;
    link.click();
    URL.revokeObjectURL(url);
}

/**
 * Sanitize filename for download
 */
function sanitizeFilename(name) {
    return name
        .replace(/[<>:"/\\|?*]/g, '')
        .replace(/\s+/g, '_')
        .substring(0, 100);
}

/**
 * Show export format selection modal
 * @param {Object} playlist - Playlist to export
 */
export function showExportModal(playlist) {
    const modal = document.createElement('div');
    modal.className = 'modal active';
    modal.innerHTML = `
        <div class="modal-overlay"></div>
        <div class="modal-content">
            <h3>Export Playlist</h3>
            <p style="margin-bottom: 1rem; color: var(--muted-foreground);">
                Export "${playlist.name || 'Untitled'}" (${playlist.tracks?.length || 0} tracks)
            </p>
            <div class="modal-list">
                <div class="modal-option" data-format="xspf" style="padding: 0.75rem; cursor: pointer; border-radius: var(--radius); display: flex; align-items: center; gap: 0.5rem;">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                        <polyline points="14,2 14,8 20,8"/>
                    </svg>
                    <div>
                        <div style="font-weight: 500;">XSPF Format</div>
                        <div style="font-size: 0.8rem; color: var(--muted-foreground);">XML Shareable Playlist Format (VLC, Winamp)</div>
                    </div>
                </div>
                <div class="modal-option" data-format="m3u" style="padding: 0.75rem; cursor: pointer; border-radius: var(--radius); display: flex; align-items: center; gap: 0.5rem;">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                        <polyline points="14,2 14,8 20,8"/>
                    </svg>
                    <div>
                        <div style="font-weight: 500;">M3U Format</div>
                        <div style="font-size: 0.8rem; color: var(--muted-foreground);">Standard playlist format (most players)</div>
                    </div>
                </div>
                <div class="modal-option" data-format="json" style="padding: 0.75rem; cursor: pointer; border-radius: var(--radius); display: flex; align-items: center; gap: 0.5rem;">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                        <polyline points="14,2 14,8 20,8"/>
                    </svg>
                    <div>
                        <div style="font-weight: 500;">JSON Format</div>
                        <div style="font-size: 0.8rem; color: var(--muted-foreground);">For importing into other Loop instances</div>
                    </div>
                </div>
            </div>
            <div class="modal-actions">
                <button class="btn-secondary cancel-btn">Cancel</button>
            </div>
        </div>
    `;
    
    document.body.appendChild(modal);
    
    // Add hover effects
    modal.querySelectorAll('.modal-option').forEach(opt => {
        opt.addEventListener('mouseenter', () => {
            opt.style.background = 'var(--secondary)';
        });
        opt.addEventListener('mouseleave', () => {
            opt.style.background = 'transparent';
        });
    });
    
    modal.addEventListener('click', (e) => {
        if (e.target.classList.contains('modal-overlay') || e.target.classList.contains('cancel-btn')) {
            modal.remove();
            return;
        }
        
        const option = e.target.closest('.modal-option');
        if (option) {
            const format = option.dataset.format;
            downloadPlaylist(playlist, format);
            modal.remove();
            
            // Show notification
            import('./downloads.js').then(({ showNotification }) => {
                showNotification(`Exported playlist as ${format.toUpperCase()}`);
            });
        }
    });
}
